### PR TITLE
Spark: Share Tranquilizers using registry in BeamRDD.

### LINKED ISSUE #158: [Spark Streaming] Background Send Thread Not Exit
I use tranquility with spark streaming for some while and I find a big problem that will make it impossible to run long enough. A [Google Group thread](https://groups.google.com/forum/#!topic/druid-user/zJXLPpDLV70) has mentioned it in Feb. 

With the streaming job running, 
```bash
jstack 69069 | grep Tranquilizer-BackgroundSend- | wc -l
```
shows that growing number of threads in waiting.
```
// com.metamx.tranquility.tranquilizer.Tranquilizer: L101

val sendThread = loggingThread {
    try {
      while (!Thread.currentThread().isInterrupted) {
        val (exIndex, exBuffer) = lock.synchronized {
          while (
            buffer.isEmpty ||
              pendingBatches.size >= maxPendingBatches ||
              (!flushing && lingerMillis > 0 && System.currentTimeMillis() < bufferStartMillis + lingerMillis)
          ) {
            if (lingerMillis == 0 || bufferStartMillis == 0) {
              lock.wait() // here
```
More and more threads in memory will at last make the streaming job exceed the memory limit and killed by yarn.

The `stop` method of `Tranquilizer` can not be called at all, for it will make the sender in next stages sent nothing! 

My solution is rather simple, manually stop the sender thread. And after doing this, the daemon threads will not grow any more.

If you need some reproducible cases, I can attach them here. I will create a PR soon later.

### PR DESCRIPTION
**Pull request by gianm**
Inspired by @du00cs fix in #159 but using a different strategy – instead of interrupting extraneous threads, try to avoid creating them in the first place by linking Tranquilizers to Beams.

Fixes #158.

### CODE REVIEW

**Comment by gianm** [comment]
Tested in https://github.com/druid-io/tranquility/pull/159#issuecomment-217154661, reported to fix the bug.

**Comment by fjy** [comment]
👍

**Comment by dclim** [comment]
cool, nice collaborative effort 👍

**Comment by drcrallen** [comment]
lol, late to the party 👍 sorry about that, this window has been open all day

**Comment by mattallty** [comment]
Hi, thanks very much for this ! Are you planning any release any time soon ?

**Comment by gianm** [comment]
@mattallty yes, hopefully sometime next week.

**Pull request merged**
