### PR TITLE
[Spark Streaming] Fix memory overhead of growing number of background send threads

### PR DESCRIPTION
**Pull request by du00cs**
See issue #158 

Simply interrupt the thread after sending will fix the issue. I think this problem make spark streaming with tranquility nearly unusable. I suffer from this for weeks...

### CODE REVIEW

**Comment by gianm** [comment]
Hmm, that this fix works that indicates we are creating WAY too many Tranquilizers. There should only be one… ideally we could fix this by sharing Tranquilizers rather than by interrupting the ones that are getting leaked.

**Comment by du00cs** [comment]
I traced for some while and find that tranquilizer is the same instance of tranquilizer, but each streaming batch (stage) will call the `start()` method to create new thread. The problem is here. I have been using the ugly interrupted one for some while, seems no problem.

**Comment by gianm** [comment]
hey @du00cs, thanks for looking into this and tracking down the problem. Could you please take a look at #168 and see if that works for you? I think that should fix this too but hopefully more nicely, without creating the extraneous threads in the first place.

**Comment by du00cs** [comment]
@gianm Thanks for fixing. I will test it.

**Comment by du00cs** [comment]
@gianm It works.

**Comment by gianm** [comment]
@du00cs thanks for testing! If you don't mind then I will close this PR and get in that other one.

**Comment by du00cs** [comment]
@gianm 👍

**Pull request closed without merging**
