### PR TITLE
[Fix] Remove data type and InputRowParser type bindings

### PR DESCRIPTION
**Pull request by du00cs**
see issue #190 

Some warnings of _type erasure_ are mentioned by compiler, seems ok. Tested with local kafka+tranquility+druid, any suggestion to write a reasonable test ?

### CODE REVIEW

**Comment by gianm** [comment]
@du00cs this test is failing in Travis: "Druid standalone - From config file - ByteBuffer type (CSV with ParseExceptions) *** FAILED ***". Does it work for you?

**Comment by du00cs** [comment]
I will try to fix it soon.

**Comment by du00cs** [comment]
@gianm  I checked again and both jdk7 and jdk8 pass the test. Something wrong with the CI?

**Comment by gianm** [comment]
@du00cs hmm, maybe, let me try running it again.

**Comment by gianm** [comment]
Looks like that was just the CI being flaky, the tests pass now. thx @du00cs

**Comment by gianm** [comment]
👍

**Pull request merged**
