### PR TITLE
Fixes #161: tranquility-flink supports only one sink operation.

### LINKED ISSUE #161: tranquility-flink supports only one sink operation?
if two BeamSink exists in one flink program, 
` getRuntimeContext.addAccumulator("Druid: Messages received", receivedCounter)`
occured error. because accumulator aleady exists.

### PR DESCRIPTION
**Pull request by gesundkrank**

### CODE REVIEW

**Comment by gianm** [comment]
👍

**Comment by nishantmonu51** [comment]
👍 @gesundkrank Please sign the CLA here - http://druid.io/community/cla.html

**Comment by gesundkrank** [comment]
@nishantmonu51 That's my 5th PR to Tranquility and I already signed it for my first (corporate CLA from mbr targeting).

Or do I have to resign it for some reason?

**Comment by nishantmonu51** [comment]
ok, no need to resign it, wasn't aware about the corporate CLA.

**Pull request merged**
