### PR TITLE
Fix doc links, add to "never exiting" section.

### PR DESCRIPTION
**Pull request by gianm**

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by rasahner** [comment]
+1, but it's always nice if a link to something goes directly to where the information being referenced appears, instead of to the top of a page that you have to read or search through.  This linked page is small enough that it doesn't really matter.

**Comment by gianm** [comment]
@rasahner I can do that, one sec

**Comment by gianm** [comment]
@rasahner updated the first link to include an anchor; I think the second one makes sense linking to the top of the page.

**Comment by rasahner** [comment]
+1

**Pull request merged**
