### PR TITLE
Cross building with Travis

### PR DESCRIPTION
**Pull request by gianm**

### CODE REVIEW

**Comment by xvrl** [comment]
@gianm can you use the same as here? https://github.com/metamx/scala-util/blob/master/.travis.yml
That should also make travis faster

**Comment by gianm** [comment]
you mean adding sudo: false?

**Comment by gianm** [comment]
ah I see, according to http://docs.travis-ci.com/user/workers/container-based-infrastructure/ that sends it to containers

**Comment by gianm** [comment]
@xvrl added sudo: false

**Comment by nishantmonu51** [comment]
+1

**Pull request merged**
