### PR TITLE
Changes to make configuration files easier to use.

### PR DESCRIPTION
**Pull request by gianm**
- No longer require "ioConfig", and remove it from the examples.
- Point out in the docs that either JSON or YAML is ok. Add sample configs and tests for JSON.
- Add tests for tuningConfig defaults.

### CODE REVIEW

**Comment by gianm** [comment]
@drcrallen this contains the promised tests from #99

**Comment by fjy** [comment]
:+1:

**Comment by gianm** [comment]
Closing for now, adjusting a couple things

**Comment by gianm** [comment]
reopened

**Comment by fjy** [comment]
@gianm failing UT

**Comment by gianm** [comment]
seems like a network issue, restarting.

```
[info] downloading https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.11/snakeyaml-1.11.jar ...
[warn] 	[FAILED     ] org.yaml#snakeyaml;1.11!snakeyaml.jar(bundle): SSL peer shut down incorrectly (95861ms)
[warn] 	[FAILED     ] org.yaml#snakeyaml;1.11!snakeyaml.jar(bundle): SSL peer shut down incorrectly (95861ms)
```

**Comment by dclim** [comment]
:+1:

**Pull request merged**
