### PR TITLE
run tests with UTC timezone

### PR DESCRIPTION
**Pull request by nishantmonu51**
the tests expect to be run from UTC timezone.

### CODE REVIEW

**Comment by drcrallen** [comment]
:+1: 

Do we need to set utf8 file type as well?

**Comment by gianm** [comment]
Which test fails when the timezone is something other than UTC? The tranquility tests should work in any time zone.

**Comment by drcrallen** [comment]
just checked master and `sbt clean test` works

**Comment by gianm** [comment]
@nishantmonu51 Are you running in IST? I wonder if something gets messed up when the UTC offset is fractional.

**Comment by nishantmonu51** [comment]
yeah, I am running with IST. 
ClusteredBeamTest fails with IST

[info] *** 12 TESTS FAILED ***
[error] Failed: Total 27, Failed 12, Errors 0, Passed 15
[error] Failed tests:
[error] 	com.metamx.tranquility.test.ClusteredBeamTest 
```
[info] - DefunctBeam *** FAILED ***
[info]   0 did not equal 1 (ClusteredBeamTest.scala:352)
[info] - Warming *** FAILED ***
[info]   Set((2012-01-01T06:00:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)))), (2012-01-01T06:00:00.000+05:30,1,false,List())) did not equal Set((2012-01-01T05:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)))), (2012-01-01T05:30:00.000+05:30,1,false,List()), (2012-01-01T06:30:00.000+05:30,0,false,List()), (2012-01-01T06:30:00.000+05:30,1,false,List())) (ClusteredBeamTest.scala:369)
[info] - WarmingConcurrency *** FAILED ***
[info]   Set((2012-01-01T06:00:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)))), (2012-01-01T06:00:00.000+05:30,1,false,List())) did not equal Set((2012-01-01T05:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)))), (2012-01-01T05:30:00.000+05:30,1,false,List()), (2012-01-01T06:30:00.000+05:30,0,false,List()), (2012-01-01T06:30:00.000+05:30,1,false,List())) (ClusteredBeamTest.scala:392)
[info] - NoBeamNecromancy *** FAILED ***
[info]   Set((2012-01-01T06:00:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:40:00.000+05:30,Map(foo -> e)))), (2012-01-01T06:00:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c))))) did not equal Set((2012-01-01T06:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c)), SimpleEvent(2012-01-01T06:40:00.000+05:30,Map(foo -> e)))), (2012-01-01T06:30:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d))))) (ClusteredBeamTest.scala:436)
[info] - NoBeamNecromancyWhenRestarting *** FAILED ***
[info]   Set((2012-01-01T06:00:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c)))), (2012-01-01T06:00:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:40:00.000+05:30,Map(foo -> e))))) did not equal Set((2012-01-01T06:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c)), SimpleEvent(2012-01-01T06:40:00.000+05:30,Map(foo -> e)))), (2012-01-01T06:30:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d))))) (ClusteredBeamTest.scala:478)
[info] - SegmentsPerBeam *** FAILED ***
[info]   Set((2012-01-01T06:00:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)), SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c)), SimpleEvent(2012-01-01T08:35:00.000+05:30,Map(foo -> g)), SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d)))), (2012-01-01T06:00:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d)), SimpleEvent(2012-01-01T08:50:00.000+05:30,Map(foo -> h))))) did not equal Set((2012-01-01T05:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T06:20:00.000+05:30,Map(foo -> b)), SimpleEvent(2012-01-01T06:30:00.000+05:30,Map(foo -> c)), SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d)))), (2012-01-01T05:30:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T06:35:00.000+05:30,Map(foo -> d)))), (2012-01-01T08:30:00.000+05:30,0,true,List(SimpleEvent(2012-01-01T08:35:00.000+05:30,Map(foo -> g)))), (2012-01-01T08:30:00.000+05:30,1,true,List(SimpleEvent(2012-01-01T08:50:00.000+05:30,Map(foo -> h))))) (ClusteredBeamTest.scala:517)
```

**Comment by nishantmonu51** [comment]
We run druid-tests also with UTC, I think it makes sense to run the tests with UTC here too.

**Comment by gianm** [comment]
Let me see if it's fixable, ideally tranquility should work regardless of your timezone.

**Comment by gianm** [comment]
I have a patch that gets the test to work in IST on top of #32, will submit a PR when that is merged

**Comment by gianm** [comment]
I think it's good for things to work in non-UTC since not everyone finds it easy to get their stream processors running in UTC

**Comment by gianm** [comment]
see #35

**Comment by fjy** [comment]
@gianm can we delete this branch?

**Comment by gianm** [comment]
yes

**Pull request closed without merging**
