### PR TITLE
DruidBeams: Respect druid.discovery.curator.path in fromConfig.

### LINKED ISSUE #150: [Feature] Auto fill discovery path from config file
`druid.discovery.curator.path` is mentioned in the [properties part](https://github.com/druid-io/tranquility/blob/master/docs/configuration.md#properties), but actually it is not loaded. I don't know if there is any connection to #62 .

Currently, I have to add lines to manually set the discovery path.

```scala
val dataSource = getDataSource(file)

instance =
   DruidBeams.fromConfig(dataSource)
       .discoveryPath(dataSource.propertiesBasedConfig.discoPath)
       .buildBeam()
```

 I think it is nice to add it to `DruidBeams` and the function
```scala
  private def fromConfigInternal[InputType, MessageType](
    inputFnFn: (DruidRollup, TimestampSpec) => (InputType => MessageType),
    timestamperFn: TimestampSpec => Timestamper[MessageType],
    config: DataSourceConfig[_ <: PropertiesBasedConfig]
  ): Builder[InputType, MessageType]
```

Maybe just one line is needed.

### PR DESCRIPTION
**Pull request by gianm**
Fixes #150.

### CODE REVIEW

**Comment by fjy** [comment]
:+1:

**Comment by nishantmonu51** [comment]
Can this break things for anyone who has already set druid.discovery.curator.path in their config but defaults were being used ?

**Comment by gianm** [comment]
In theory yes, although if someone set `druid.discovery.curator.path` to something wrong then that's kind of strange. But, yes, that could happen.

btw, till now this property was respected for Server and Kafka, but not Core (i.e. `DruidBeams.fromConfig`).

**Comment by nishantmonu51** [comment]
+1, Added release notes label so that we dont forget to mention this.

**Comment by KurtYoung** [comment]
Can you release a SNAPSHOT version for this issue? We are stuck with this issue or do you have any way to workaround with 0.7.4?

**Comment by KurtYoung** [comment]
never mind, i built a 0.7.5-SNAPSHOT myself :-)

**Pull request merged**
